// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChazPiXHF2cknu6GsQKIOxhfT8QDWIngk',
    appId: '1:51201876750:android:fb75e30260f9a80804ad5f',
    messagingSenderId: '51201876750',
    projectId: 'learn-firebase-project-84ece',
    databaseURL: 'https://learn-firebase-project-84ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-project-84ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0c-ahkrTZcN56Rx6wPctEcxlD9Hhy06g',
    appId: '1:51201876750:ios:15255ab573c4824f04ad5f',
    messagingSenderId: '51201876750',
    projectId: 'learn-firebase-project-84ece',
    databaseURL: 'https://learn-firebase-project-84ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-project-84ece.appspot.com',
    androidClientId: '51201876750-egmqgjhbtvkt6cj3hkvh2k1o4aft9h8a.apps.googleusercontent.com',
    iosClientId: '51201876750-57r9jbrgturbu8jjlstvqm0189mctg8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );
}
