// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21hi27eTG-yqNcpd_bgK093bLEXjxlIg',
    appId: '1:51201876750:web:87796015f543ce0404ad5f',
    messagingSenderId: '51201876750',
    projectId: 'learn-firebase-project-84ece',
    authDomain: 'learn-firebase-project-84ece.firebaseapp.com',
    databaseURL: 'https://learn-firebase-project-84ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-project-84ece.appspot.com',
    measurementId: 'G-FH997182QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChazPiXHF2cknu6GsQKIOxhfT8QDWIngk',
    appId: '1:51201876750:android:2bad6af5e577432b04ad5f',
    messagingSenderId: '51201876750',
    projectId: 'learn-firebase-project-84ece',
    databaseURL: 'https://learn-firebase-project-84ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-project-84ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0c-ahkrTZcN56Rx6wPctEcxlD9Hhy06g',
    appId: '1:51201876750:ios:3cb1210c6229f0e704ad5f',
    messagingSenderId: '51201876750',
    projectId: 'learn-firebase-project-84ece',
    databaseURL: 'https://learn-firebase-project-84ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-firebase-project-84ece.appspot.com',
    androidClientId: '51201876750-0rho1vlf2ju3lmov557tp6uvfub58eag.apps.googleusercontent.com',
    iosClientId: '51201876750-0b2nf1lu1mqa6bbgmruack5cjtv64uhq.apps.googleusercontent.com',
    iosBundleId: 'com.bharatiya.food',
  );
}
